Update/add osmosis test tube
AbstractSDK/cw-orchestrator pull request #150
Opened 2023-07-05 11:20 UTC by Kayanski

This PR aims at providing Osmosis-test-tube as an additional chain for cw-orch. 
This new chain is very similar to cw-multi-test but tests against actual on-chain logic.
Basic counter tests have been provided

2023-07-06 11:05 UTC, CyberHoward commented on cw-orch/Cargo.toml
> -default = []
we shouldn't have it default

2023-07-06 11:15 UTC, CyberHoward requested changes
Wow, that's so little code for an integration, pretty awesome. 

Is there any pre-setup required to executing with this? I.e. is the binary included in the package or does the user need to install anything before they can run this? If so it should be clearly documented somewhere.

2023-07-06 11:15 UTC, CyberHoward commented on cw-orch/src/test_tube/core.rs
> +/// Wrapper around a cw-multi-test [`App`](cw_multi_test::App) backend.
These doc comments should be updated

2023-07-06 11:15 UTC, CyberHoward commented on cw-orch/src/test_tube/core.rs
> +    pub fn new(init_coins: Vec<Coin>) -> Self {
To who are these init coins minted? Add some doc comment on that

2023-07-06 11:15 UTC, CyberHoward commented on cw-orch/src/test_tube/response.rs
This file seems empty

2023-07-06 11:17 UTC, CyberHoward commented
Oh and can we rename TestTube to OsmosisTestTube? I think the idea of test-tube is to allow other chains to use it as well, so there could be a NeutronTestTube, etc.

2023-07-07 10:34 UTC, CyberHoward commented on README.md
> +OsmosisTestTube is available for testing in cw-orchestrator. In order to use it, you may need to install [clang] and [go] to compile the osmosis blockchain that serves as the backend for this env.
Is the compilation done by the crate or is there other setup? A link to the test-tube repo would be great here as well.

2023-07-07 10:37 UTC, CyberHoward commented
And could you add a usage example in /cw-orch/examples ? You need to add it to the cargo.toml as well and set the feature requirement

2023-07-08 14:29 UTC, Kayanski commented
> 

Done

2023-07-09 15:03 UTC, CyberHoward approved these changes

2023-07-09 15:03 UTC, merged