Fix the ExecuteMsgFns macro in case there is a where clause
AbstractSDK/cw-orchestrator pull request #193
Opened 2023-08-16 14:49 UTC by Kayanski

This PR aims at fixing the macro when you are creating the ExecuteMsgFns macro along with a generic type and a where clause

2023-08-16 14:51 UTC, CyberHoward requested changes
Could you add a test-case?

2023-08-16 15:20 UTC, Kayanski commented
T

> Could you add a test-case?

Added tests.
Test are failing because we need to update osmosis-std to fix them. It's already fixed in  : https://github.com/AbstractSDK/cw-orchestrator/pull/152

2023-08-16 18:31 UTC, Buckram123 approved these changes
That's pretty cool

2023-08-16 18:31 UTC, Buckram123 commented on packages/cw-orch-fns-derive/src/execute_fns.rs
> +        pub trait #bname<Chain: ::cw_orch::prelude::CwEnv, #type_generics>: ::cw_orch::prelude::CwOrchExecute<Chain, ExecuteMsg = #entrypoint_msg_type #ty_generics> #where_clause {
:exploding_head:

2023-08-16 18:31 UTC, Buckram123 commented on packages/cw-orch-fns-derive/src/execute_fns.rs
> +
Nice approach

2023-08-17 08:10 UTC, CyberHoward commented
> T
> 
> > Could you add a test-case?
> 
> Added tests. Test are failing because of the way osmosis handles dependencies and versions. There are some misdependencies between osmosis test tube packages

Could we get the tests resolved before merging this?

2023-08-17 09:22 UTC, CyberHoward commented
Created an issue on test-tube: https://github.com/osmosis-labs/test-tube/issues/38

2023-08-17 09:24 UTC, CyberHoward approved these changes

2023-08-17 09:24 UTC, merged