Added better state_dir management + Exposed state_dir method
AbstractSDK/cw-orchestrator pull request #245
Opened 2023-09-29 09:44 UTC by Kayanski

This PR aims at using only the dirs crate to generate the statedir (~/.cw-orchestrator).

This is a non-breaking change.

2023-10-10 15:17 UTC, Buckram123 requested changes
Let's have better error management as well

2023-10-11 12:07 UTC, Kayanski commented on cw-orch-daemon/src/state.rs
> +    }
You are right ! I Added an error in case this doesn't exist. It allows users to simply recover from that error as well (using the error message)

2023-10-11 12:55 UTC, Buckram123 approved these changes
LGTM!

2023-10-11 12:55 UTC, Buckram123 commented on packages/cw-orch-core/src/env.rs
> +}
Love it!

2023-10-11 12:55 UTC, Buckram123 commented on CHANGELOG.md
> +- Exposed the state_dir location
Don't forget to add envs update to the changelog!

2023-10-11 12:55 UTC, Buckram123 commented on cw-orch-daemon/src/state.rs
> +                    CwOrchEnvVars::StateFolder.name()
Any specific reason you decided to use `name()` method instead of implementing Display trait btw?

2023-10-11 12:55 UTC, Buckram123 commented on docs/src/single_contract/env-variable.md
> +You can find a more up-to-date version of all env variables that are specific to `cw-orch` in the [`cw_orch_core::env` file](https://github.com/AbstractSDK/cw-orchestrator/blob/main/packages/cw-orch-
:fire:

2023-10-11 12:59 UTC, Buckram123 commented on cw-orch-daemon/src/state.rs
> +    }
> What about now, what do you think ? I followed your advice and centralized all `cw-orch` specific env variables

Didn't expect you to do it that quickly! Was just thinking sharing an idea. But it looks so cool now!

2023-10-11 13:30 UTC, Kayanski commented on cw-orch-daemon/src/state.rs
> +    }
I liked the idea and was working on it :)

2023-10-12 13:14 UTC, CyberHoward approved these changes

2023-10-12 16:05 UTC, merged